name: vision-language-similarity-local
services:
  evaluator:
    image: local/vision_language_similarity_service:latest
    command: uvicorn service.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
      - "8080:8080"  # Metrics port
    environment:
      - PYTHONPATH=/app
      # Local development configuration
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - MODEL_MAX_WORKERS=2
      - MODEL_TIMEOUT=30.0
      - MODEL_CACHE_DIR=/app/model-cache
      - ENABLE_MIXED_PRECISION=true
      - GPU_MEMORY_FRACTION=0.8
      - MAX_BATCH_SIZE=50
      - MAX_IMAGE_SIZE_MB=10
      - RATE_LIMIT_PER_MINUTE=500
      - ENABLE_METRICS=true
      - ENABLE_TRACING=true
      - METRICS_PORT=8080
      # Example: Add model via environment variable
      - |
        MODEL_CONFIG_LOCAL={
          "models": {
            "fast": {
              "model_name": "ViT-B-32",
              "pretrained": "laion2b_s34b_b79k",
              "description": "Faster inference, good performance",
              "enabled": true
            },
            "accurate": {
              "model_name": "ViT-L-14",
              "pretrained": "laion2b_s32b_b82k",
              "description": "Higher accuracy, slower inference",
              "enabled": true
            },
            "experimental": {
              "model_name": "ViT-B-16",
              "pretrained": "laion2b_s34b_b79k",
              "description": "Experimental balanced model",
              "enabled": false
            },
            "custom": {
              "model_name": "ViT-L-14-336",
              "pretrained": "openai",
              "description": "Custom high-resolution model",
              "enabled": false
            }
          }
        }
    volumes:
      # Mount cache directory to persist model downloads
      - model_cache:/app/model-cache
      # Optional: Mount source code for development
      - ../service:/app/service:ro
    env_file:
      - ${PWD}/.env.local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/evaluator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  model_cache: