receivers:        
  prometheus:
    config:
      scrape_configs:
      - job_name: 'vision-similarity-service'
        scrape_interval: 10s
        metrics_path: "/evaluator/metrics"
        static_configs:
        - targets: ['vision-similarity-service:8000']

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

  # Add resource attributes
  resource:
    attributes:
    - action: upsert
      key: service.name
      value: vision-similarity-service
    - action: upsert  
      key: service.version
      value: 0.1.0

exporters:
  # Export metrics to Prometheus via remote write
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    resource_to_telemetry_conversion:
      enabled: true

  # Debug exporter for troubleshooting
  debug:
    verbosity: basic

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [resource, batch] 
      exporters: [debug, prometheusremotewrite]

  telemetry:
    logs:
      level: info
    metrics:
      address: 0.0.0.0:8889